import React from "react";
import Footer from "../components/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Default({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#FFF2D8] w-full min-h-screen">
        {children}
        <Footer />
      </body>
    </html>
  );
}
